### ISSUE TITLE
Suggestions: Additions and changes to gobelt DAO gen

### ISSUE THREAD

**Issue by wscherfel** [flowup/gobelt#16]
Suggestions can be added to this issue, after gathering data changes will be implemented.

My suggestions:
1. Rename DAO mocks because they are not real mocks, its working in memory DB
2. Add flag to turn off In memory DB DAO generation
3. Generate in memory DB DAOs to another file (discuss creating DAOs for every model to separate files)
4. Add `GetMap` method that returns full in memory DB indexed by IDs, or make the map field of in memory DAOs exported
5. @kubaj suggested that it could generate DAOs in set order (e.g. alphabetical ordering of parsed models), so that LOC changes in commits is not that high (6k additions and 3k deletions in one DAO regeneration). 
6. In memory DB constructors could have a flag that would determine if the in memory DB would generate IDs automatically (and overwrite any IDs filled by user) or if the DB user would fill them manually.
7. Add `Reset` method to in memory DB DAOs for reseting DB to empty state.

**Comment by rysavyvladan** [comment]
DAO method delete all 
Drop mock db
Able specific own IDs for create to mock db
